@startuml
class Logger{
        + $dateFormat = DateTime::RFC2822;
        + $filePath;
        + $template = "{date} {level} {message} {context}";
        - $level;
    
        +  __construct(array $attributes = [])    
        +  initialize(array $attributes = [])
        +  log($level, $message, array $context = [])
        +  getDate()
        +  contextStringify(array $context = [])
        +  getLevel()
}

@enduml