@startuml

class Singleton{
    {static} - $instance = null;
    -  __construct()
    -  __clone()
    -  __wakeup()
    {static} +  getInstance()
}

class Router extends Singleton{
    - $routes = [];
    - $routeTypes = ['POST' => true, 'GET' => true];

    +  initialize(array $config = [])
    -  parseHooks($params = '')
    -  setRoute(Route $parsedRoute)
    -  parseRoute(array $route)//TODO rename because method create instance after hook is parsed
    +  disableRouterType($type)
    +  getCurrentRoutParams($uri, $base, $method)
    -  getRegex($pattern)
    +  getRoutes(): array
    +  getRouteTypes(): array
}

@enduml