@startuml

class Session{
    # $lifeTime;
    - $sess;
    - $prefix;
    - $path;
    - $domain;
    - $name;
    -  __construct()
    +  initialize()
    +  isEnabled()
    +  set($key, $val)
    +  get($key)
    +  delete($key)
    +  start()
    +  clear()
    +  destroy()
}

@enduml