@startuml

interface IStructure{
    + select()
    + delete()
    + insert()
    + update()
}
interface IStructureSQL implements IStructure{
    + getFieldsString()
    + withJoin()
    + withWhere()
    + withInsert()
}

@enduml